source = ./modules/colors.conf

$text = $foreground
$font = "JetBrainsMono"

# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND
background {
  path = $HOME/.wallpapers/waifu.jpg
  blur_size = 1
  blur_passes = 4
  brightness = 0.2
}

# LAYOUT
label {
  monitor =
  text = Layout: $LAYOUT
  color = $text
  font_size = 10
  font_family = $font
  position = 30, -30
  halign = left
  valign = top
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 2
  dots_size = 0.1
  dots_spacing = 0.1
  dots_center = true
  outer_color = $primary
  inner_color = $background
  font_color = $foreground
  fade_on_empty = false
  placeholder_text = <i>password...</i>
  font_family = $font
  hide_input = false
  check_color = $foreground
  fail_color = $backgroundAlt
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, 0
  halign = center
  valign = center
  rounding = 0
}