wallpaper {
    monitor = DP-1
    path = ~/.dotfiles/.wallpapers/omen.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/.dotfiles/.wallpapers/omen.jpg
    fit_mode = cover
}

splash = false