# See https://wiki.hypr.land/Configuring/Keywords/
$MAINMOD = SUPER # Sets "Windows" key as main modifier

$terminal = alacritty
$fileManager = dolphin
$menu = sh ~/.config/rofi/launcher.sh


# Core
bind = CTRL ALT, right, exec, hyprshot -m region
bind = , PRINT, exec, grim
bind = $MAINMOD ALT, C, exec, hyprpicker -a
bind = CTRL ALT, T, exec, $terminal
bind = CTRL ALT, Delete, exec, $terminal
bind = $MAINMOD, Q, exec, $terminal

bind = $MAINMOD, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $MAINMOD, E, exec, $fileManager
bind = $MAINMOD, Space, exec, $menu
bind = $MAINMOD, P, pseudo, # dwindle
bind = $MAINMOD, J, togglesplit, # dwindle

$power = eww close powerconfirm; eww open powermenu --toggle --screen $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).id')
# $power = sh ~/.config/rofi/powermenu.sh
bind = , Home, exec, $power
bind = , Esc, exec, eww close powermenu

# Window Management
bind = $MAINMOD, End, killactive
bind = $MAINMOD, W, killactive
bind = $MAINMOD SHIFT, W, exec, hyprctl dispatch kill

bind = $MAINMOD, F, fullscreen
bind = $MAINMOD, V, togglefloating
bind = $MAINMOD, Tab, focuscurrentorlast
bind = $MAINMOD, R, cyclenext

bind = $MAINMOD, left, movefocus, l
bind = $MAINMOD, right, movefocus, r
bind = $MAINMOD, up, movefocus, u
bind = $MAINMOD, down, movefocus, d

bind = $MAINMOD SHIFT, H, swapwindow, l
bind = $MAINMOD SHIFT, J, swapwindow, d
bind = $MAINMOD SHIFT, K, swapwindow, u
bind = $MAINMOD SHIFT, L, swapwindow, r


# Move/resize windows with MAINMOD + LMB/RMB and dragging
bindm = $MAINMOD, mouse:272, movewindow
bindm = $MAINMOD, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
