$M_MONITOR = DP-1
$S_MONITOR = DP-3

workspace = 1, monitor:$M_MONITOR, default:true
workspace = 2, monitor:$M_MONITOR
workspace = 3, monitor:$M_MONITOR
workspace = 4, monitor:$M_MONITOR

workspace = 5, monitor:$S_MONITOR
workspace = 6, monitor:$S_MONITOR
workspace = 7, monitor:$S_MONITOR

plugin {
    split-monitor-workspaces {
        count = 4
        keep_focused = 0
        enable_notifications = 0
        enable_persistent_workspaces = 1

        # set this to 1 for gnome-like workspace switching
        link_monitors = 1

        # if you want a different monitor order
        monitor_priority = $M_MONITOR, $S_MONITOR

        # you can also set max workspaces per monitor
        max_workspaces = $M_MONITOR, 4
        max_workspaces = $S_MONITOR, 4
    }
}

# Switch workspaces with MAINMOD + [0-9]
bind = $MAINMOD, 1, workspace, 1
bind = $MAINMOD, 2, workspace, 2
bind = $MAINMOD, 3, workspace, 3
bind = $MAINMOD, 4, workspace, 4

bind = $MAINMOD, 5, workspace, 5
bind = $MAINMOD, 6, workspace, 6
bind = $MAINMOD, 7, workspace, 7
bind = $MAINMOD, 8, workspace, 8

# Move active window to a workspace with MAINMOD + SHIFT + [0-9]
bind = $MAINMOD SHIFT, 1, split-movetoworkspace, 1
bind = $MAINMOD SHIFT, 2, split-movetoworkspace, 2
bind = $MAINMOD SHIFT, 3, split-movetoworkspace, 3
bind = $MAINMOD SHIFT, 4, split-movetoworkspace, 4

bind = $MAINMOD SHIFT, 5, split-movetoworkspace, 5
bind = $MAINMOD SHIFT, 6, split-movetoworkspace, 6
bind = $MAINMOD SHIFT, 7, split-movetoworkspace, 7
bind = $MAINMOD SHIFT, 8, split-movetoworkspace, 8

bind = $MAINMOD, mouse_down, workspace, e+1
bind = $MAINMOD, mouse_up, workspace, e-1
