[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

[colors.cursor]
cursor = "#ffffff"
text = "#F81CE5"

[font]
size = 16

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "SemiBold"

[window]
opacity = 0.8

[window.padding]
x = 10
y = 10
